/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanasproyecto;

import javax.swing.JDialog;

/**
 *
 * @author VikAle
 */
public class VentanaReportes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReportes
     */
    int selector = 0;
    VentanaPrincipal vAnterior;
    ventanaLogin ventanaHome;
    public VentanaReportes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        LabelSeleccion = new javax.swing.JLabel();
        LabelFechaIni = new javax.swing.JLabel();
        LabelFechaFin = new javax.swing.JLabel();
        AcceptDialog = new javax.swing.JButton();
        ClientesFrameReport = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        MasVendidoFrameReport = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        VentasFrameReport = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        VentasContFrameReport = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        BalanceFrameReport = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        SelecionRep = new javax.swing.JLabel();
        ButtRepClientes = new javax.swing.JButton();
        ButtProdMasVend = new javax.swing.JButton();
        ButtRepMensVentas = new javax.swing.JButton();
        ButtRepVentasCont = new javax.swing.JButton();
        ButtRepBalance = new javax.swing.JButton();
        ButtRepCerrar = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.getContentPane().setLayout(null);

        LabelSeleccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelSeleccion.setText("Seleccione un rango de fecha");
        jDialog1.getContentPane().add(LabelSeleccion);
        LabelSeleccion.setBounds(10, 20, 230, 17);

        LabelFechaIni.setText("Fecha Inicial");
        jDialog1.getContentPane().add(LabelFechaIni);
        LabelFechaIni.setBounds(10, 60, 90, 16);

        LabelFechaFin.setText("Fecha Final");
        jDialog1.getContentPane().add(LabelFechaFin);
        LabelFechaFin.setBounds(10, 100, 80, 16);

        AcceptDialog.setText("Aceptar");
        AcceptDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptDialogActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(AcceptDialog);
        AcceptDialog.setBounds(117, 150, 110, 25);

        ClientesFrameReport.getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "N° Visitas", "Ingreso Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        ClientesFrameReport.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 480, 140);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Reporte de Clientes más frecuentes");
        ClientesFrameReport.getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 27, 321, 22);

        MasVendidoFrameReport.getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cant. Vendidos", "Monto Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        MasVendidoFrameReport.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(59, 83, 375, 131);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Reporte de productos más vendidos");
        MasVendidoFrameReport.getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 30, 340, 22);

        VentasFrameReport.getContentPane().setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo Doc.", "N° Recibo", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        VentasFrameReport.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(57, 100, 375, 156);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Reporte de Ventas");
        VentasFrameReport.getContentPane().add(jLabel13);
        jLabel13.setBounds(150, 50, 180, 22);

        VentasContFrameReport.getContentPane().setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipo Doc.", "N° Doc.", "Fecha", "Monto sin IGV", "IGV", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        VentasContFrameReport.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 110, 562, 119);

        jLabel1.setText("Ventas");
        VentasContFrameReport.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 70, 16);

        jLabel2.setText("Compras");
        VentasContFrameReport.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 240, 80, 16);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Factura", "Fecha", "Monto sin IGV", "IGV", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        VentasContFrameReport.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(10, 260, 562, 123);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Reporte de documentos contables");
        VentasContFrameReport.getContentPane().add(jLabel14);
        jLabel14.setBounds(130, 40, 320, 22);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        BalanceFrameReport.getContentPane().setLayout(null);

        jLabel3.setText("Ventas totales");
        BalanceFrameReport.getContentPane().add(jLabel3);
        jLabel3.setBounds(19, 62, 140, 16);

        jLabel4.setText("Servicios");
        BalanceFrameReport.getContentPane().add(jLabel4);
        jLabel4.setBounds(19, 93, 150, 16);

        jLabel5.setText("Alquiler");
        BalanceFrameReport.getContentPane().add(jLabel5);
        jLabel5.setBounds(19, 124, 160, 16);

        jLabel6.setText("Pago empleados");
        BalanceFrameReport.getContentPane().add(jLabel6);
        jLabel6.setBounds(19, 153, 170, 16);

        jLabel7.setText("Compras");
        BalanceFrameReport.getContentPane().add(jLabel7);
        jLabel7.setBounds(19, 178, 150, 16);

        jLabel8.setText("Otros");
        BalanceFrameReport.getContentPane().add(jLabel8);
        jLabel8.setBounds(19, 209, 150, 16);

        jTextField1.setEnabled(false);
        BalanceFrameReport.getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 60, 88, 22);

        jTextField2.setEnabled(false);
        BalanceFrameReport.getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 90, 88, 22);

        jTextField3.setEnabled(false);
        BalanceFrameReport.getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 120, 88, 22);

        jTextField4.setEnabled(false);
        BalanceFrameReport.getContentPane().add(jTextField4);
        jTextField4.setBounds(200, 180, 88, 22);

        jTextField5.setEnabled(false);
        BalanceFrameReport.getContentPane().add(jTextField5);
        jTextField5.setBounds(200, 150, 88, 22);

        jTextField6.setEnabled(false);
        BalanceFrameReport.getContentPane().add(jTextField6);
        jTextField6.setBounds(200, 250, 88, 22);
        BalanceFrameReport.getContentPane().add(jSeparator1);
        jSeparator1.setBounds(19, 237, 280, 10);

        jLabel9.setText("Utilidad");
        BalanceFrameReport.getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 250, 150, 16);

        jTextField7.setEnabled(false);
        BalanceFrameReport.getContentPane().add(jTextField7);
        jTextField7.setBounds(200, 210, 88, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Reporte de Ingresos y Egresos");
        BalanceFrameReport.getContentPane().add(jLabel10);
        jLabel10.setBounds(77, 11, 274, 22);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelecionRep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelecionRep.setText("Seleccione un reporte a generar");

        ButtRepClientes.setText("Clientes frecuentes");
        ButtRepClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtRepClientesMouseClicked(evt);
            }
        });
        ButtRepClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtRepClientesActionPerformed(evt);
            }
        });

        ButtProdMasVend.setText("Productos más vendidos");
        ButtProdMasVend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtProdMasVendMouseClicked(evt);
            }
        });

        ButtRepMensVentas.setText("Ventas");
        ButtRepMensVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtRepMensVentasMouseClicked(evt);
            }
        });

        ButtRepVentasCont.setText("Documentos para Contabilidad");
        ButtRepVentasCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtRepVentasContMouseClicked(evt);
            }
        });
        ButtRepVentasCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtRepVentasContActionPerformed(evt);
            }
        });

        ButtRepBalance.setText("Ingresos y egresos");
        ButtRepBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtRepBalanceMouseClicked(evt);
            }
        });

        ButtRepCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        ButtRepCerrar.setText("Volver");
        ButtRepCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtRepCerrarMouseClicked(evt);
            }
        });
        ButtRepCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtRepCerrarActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        logout.setText("Cerrar Sesión");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtRepBalance)
                    .addComponent(ButtRepVentasCont)
                    .addComponent(ButtRepMensVentas)
                    .addComponent(ButtProdMasVend)
                    .addComponent(ButtRepClientes)
                    .addComponent(SelecionRep, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtRepCerrar)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SelecionRep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ButtRepClientes)
                .addGap(30, 30, 30)
                .addComponent(ButtProdMasVend)
                .addGap(26, 26, 26)
                .addComponent(ButtRepMensVentas)
                .addGap(30, 30, 30)
                .addComponent(ButtRepVentasCont)
                .addGap(26, 26, 26)
                .addComponent(ButtRepBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtRepCerrar)
                    .addComponent(logout))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void abrirReporte(int n){
        switch(n){
            case 1:
                ClientesFrameReport.setVisible(true);
                break;
            case 2:
                MasVendidoFrameReport.setVisible(true);
                break;
            case 3:
                VentasFrameReport.setVisible(true);
                break;
            case 4:
                VentasContFrameReport.setVisible(true);
                break;
            case 5:
                BalanceFrameReport.setVisible(true);
                break;
        }
    }
    
    private void ButtRepCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtRepCerrarMouseClicked
        
    }//GEN-LAST:event_ButtRepCerrarMouseClicked

    private void ButtRepClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtRepClientesMouseClicked
        selector = 1;
        jDialog1.setVisible(true);                
    }//GEN-LAST:event_ButtRepClientesMouseClicked

    private void ButtRepClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtRepClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtRepClientesActionPerformed

    private void AcceptDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptDialogActionPerformed
        jDialog1.dispose();
        abrirReporte(selector);
    }//GEN-LAST:event_AcceptDialogActionPerformed

    private void ButtProdMasVendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtProdMasVendMouseClicked
        selector = 2;
        jDialog1.setVisible(true);
    }//GEN-LAST:event_ButtProdMasVendMouseClicked

    private void ButtRepMensVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtRepMensVentasMouseClicked
        selector = 3;
        jDialog1.setVisible(true);
    }//GEN-LAST:event_ButtRepMensVentasMouseClicked

    private void ButtRepVentasContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtRepVentasContMouseClicked
        selector = 4;
        jDialog1.setVisible(true);
    }//GEN-LAST:event_ButtRepVentasContMouseClicked

    private void ButtRepBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtRepBalanceMouseClicked
        selector = 5;
        jDialog1.setVisible(true);
    }//GEN-LAST:event_ButtRepBalanceMouseClicked

    private void ButtRepVentasContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtRepVentasContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtRepVentasContActionPerformed

    private void ButtRepCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtRepCerrarActionPerformed
        // TODO add your handling code here:
        vAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtRepCerrarActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        ventanaHome.regresar();
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptDialog;
    private javax.swing.JFrame BalanceFrameReport;
    private javax.swing.JButton ButtProdMasVend;
    private javax.swing.JButton ButtRepBalance;
    private javax.swing.JButton ButtRepCerrar;
    private javax.swing.JButton ButtRepClientes;
    private javax.swing.JButton ButtRepMensVentas;
    private javax.swing.JButton ButtRepVentasCont;
    private javax.swing.JFrame ClientesFrameReport;
    private javax.swing.JLabel LabelFechaFin;
    private javax.swing.JLabel LabelFechaIni;
    private javax.swing.JLabel LabelSeleccion;
    private javax.swing.JFrame MasVendidoFrameReport;
    private javax.swing.JLabel SelecionRep;
    private javax.swing.JFrame VentasContFrameReport;
    private javax.swing.JFrame VentasFrameReport;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
