/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanasproyecto;

import LogicaNegocio.ProductoBL;
import clases.LineaxCompra;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author VikAle
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ProductoBL LogicaNegocio;
    public VentanaPrincipal() throws ClassNotFoundException, SQLException {
        initComponents();
        LogicaNegocio = new ProductoBL();
        listarProxVencimiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        compras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        optionLbel = new javax.swing.JLabel();
        nomb1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Jefe");
        setMinimumSize(new java.awt.Dimension(410, 430));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 0, 0);

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 150, 150, 70);

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Administrador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 240, 150, 70);

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Reportes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 240, 150, 70);

        compras.setBackground(new java.awt.Color(255, 255, 204));
        compras.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        compras.setText("Compras");
        compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprasMouseClicked(evt);
            }
        });
        compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasActionPerformed(evt);
            }
        });
        getContentPane().add(compras);
        compras.setBounds(200, 150, 150, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido");
        jLabel1.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 14));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 30, 147, 44);

        optionLbel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        optionLbel.setText("Elija una opción:");
        getContentPane().add(optionLbel);
        optionLbel.setBounds(27, 107, 160, 22);

        nomb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nomb1.setText("usuario");
        getContentPane().add(nomb1);
        nomb1.setBounds(220, 40, 140, 29);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        jButton6.setText("Cerrar Sesión");
        jButton6.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(220, 340, 130, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarProxVencimiento() throws ClassNotFoundException, SQLException{
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date fecha1 = new java.util.Date();
        String fecha = sdf.format(fecha1);
        ArrayList<LineaxCompra> lista = LogicaNegocio.listarProxVencimiento(fecha);
        if(lista.size()>0){
            ventanaAlerta alerta = new ventanaAlerta(lista);
            alerta.setVisible(true);
            alerta.setLocationRelativeTo(null);
            alerta.setFocusable(true);
        }
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprasMouseClicked
    ventanaCompra ventCmp = new ventanaCompra();
    ventCmp.setLocationRelativeTo(null);
    ventCmp.setVisible(true);
    ventCmp.vAnterior = this;
    ventCmp.ventanaHome = this.ventanaHome;
    this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_comprasMouseClicked

    private void comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprasActionPerformed
    ventanaLogin ventanaHome;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null, "¿Desea cerrar sesión?","Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0){
            ventanaHome.regresar();
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ventanaAdmin v1 = new ventanaAdmin();
        v1.vAnterior = this;
        v1.jButton7.setVisible(true);
        v1.jButton1.setVisible(false);
        v1.anterior = "Jefe";
        v1.nomb.setText(nomb1.getText());
        v1.ventanaHome = this.ventanaHome;
        v1.setLocationRelativeTo(null);
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VentanaReportes v1 = new VentanaReportes();
        v1.vAnterior = this;
        v1.ventanaHome = this.ventanaHome;
        v1.setLocationRelativeTo(null);
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane2;
    public static javax.swing.JLabel nomb1;
    private javax.swing.JLabel optionLbel;
    // End of variables declaration//GEN-END:variables
}
