/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanasproyecto;

import LogicaNegocio.ProductoBL;
import clases.Consumible;
import clases.NoConsumible;
import clases.Producto;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alulab14
 */
public class ventanaManProd extends javax.swing.JFrame {

    /**
     * Creates new form ventanaManProd
     */
    
    private ProductoBL LogicaNegocio;
      
    public ventanaManProd() throws ClassNotFoundException, SQLException {
        this.setTitle("Mantener Productos");
        this.setLocationRelativeTo(null);
        
        initComponents();
        tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
        LogicaNegocio = new ProductoBL();
        listarProductos();
        registrar.setEnabled(false);
        modificar.setEnabled(false);
        eliminar.setEnabled(false);
        
        idU =0;
    }
    ventanaAdmin ventanaAnterior;
    int idU;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        cantMin = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        registrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        consum = new javax.swing.JRadioButton();
        no_consum = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mantener Producto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 175, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 51, 60, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 80, 60, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Cantidad Minima:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 109, 110, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Marca:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 138, 50, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Tipo Producto:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 196, 100, 16);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre);
        nombre.setBounds(154, 48, 200, 22);
        getContentPane().add(precio);
        precio.setBounds(154, 77, 200, 22);
        getContentPane().add(cantMin);
        cantMin.setBounds(154, 106, 200, 22);
        getContentPane().add(marca);
        marca.setBounds(154, 135, 200, 22);

        tabla.setBackground(new java.awt.Color(255, 255, 204));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Marca", "Tipo", "Categoria"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 310, 380, 130);

        registrar.setBackground(new java.awt.Color(255, 255, 204));
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar);
        registrar.setBounds(40, 270, 90, 30);

        modificar.setBackground(new java.awt.Color(255, 255, 204));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar);
        modificar.setBounds(180, 270, 90, 30);

        eliminar.setBackground(new java.awt.Color(255, 255, 204));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar);
        eliminar.setBounds(310, 270, 90, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        jButton4.setText("Cerrar Sesión");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 460, 140, 29);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(140, 460, 110, 29);

        consum.setText("Consumible");
        consum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumActionPerformed(evt);
            }
        });
        getContentPane().add(consum);
        consum.setBounds(150, 193, 95, 25);

        no_consum.setText("No Consumible");
        no_consum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_consumActionPerformed(evt);
            }
        });
        getContentPane().add(no_consum);
        no_consum.setBounds(250, 193, 120, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Descripción:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 167, 130, 16);
        getContentPane().add(desc);
        desc.setBounds(154, 164, 200, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Categoria:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(12, 225, 110, 16);

        getContentPane().add(categoria);
        categoria.setBounds(154, 222, 200, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isDouble(String cadena) {

        boolean resultado;

        try {
            Double.parseDouble(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }
    
    private boolean validarInput(){
        String s = this.nombre.getText();
        if((s).equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos activos vacios", "Error Null", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        for (int i=0; i<s.length(); i++){
            if(!((s.charAt(i)>='a' && s.charAt(i)<='z')||(s.charAt(i)>='A' && s.charAt(i)<='Z') || s.charAt(i) == 'ñ' || s.charAt(i) == 'Ñ' || s.charAt(i)== ' ')){
                JOptionPane.showMessageDialog(null, "campo nombre solo puede contener letras", "Error Nombre", JOptionPane.PLAIN_MESSAGE);
                return false;
            }
        }
        s = this.precio.getText();
        if((s).equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos activos vacios", "Error Null", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        if(!isDouble(s)){
            JOptionPane.showMessageDialog(null, "Precio debe ser un valor real", "Error Sueldo", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        s = this.cantMin.getText();
        if((s).equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos activos vacios", "Error Null", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        for (int i=0; i<s.length(); i++){
            if(!(s.charAt(i)>='0' && s.charAt(i)<='9')){
                JOptionPane.showMessageDialog(null, "la cantidad debe ser un entero", "Error Numerico", JOptionPane.PLAIN_MESSAGE);
                return false;
            }
        }
        s = this.marca.getText();
        if((s).equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos activos vacios", "Error Null", JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        
    
        
                          
        return true;
    }
    
    private void listarProductos() throws ClassNotFoundException, SQLException{
        ArrayList<Producto> arr = new ArrayList<Producto>();
        arr = LogicaNegocio.listarProductos();
        model = (javax.swing.table.DefaultTableModel)tabla.getModel();
        int n = arr.size();
        int r = model.getRowCount();
        for (int j=0; j<r; j++){
            model.removeRow(0);
        }
        for (int i=0; i<n; i++){
            String con = "";
            String cat = "";
            if(arr.get(i) instanceof Consumible){
                con = "Consumible";
                cat = ((Consumible) arr.get(i)).getCategoria().toString();
            }else if(arr.get(i) instanceof NoConsumible){
                con = "NoConsumible";
                cat = ((NoConsumible) arr.get(i)).getCategoria().toString();
            }
            Object o[] = {arr.get(i).getIdProducto(), arr.get(i).getNombre(), arr.get(i).getPrecio(), arr.get(i).getMarca(), con, cat};
            model.addRow(o);
        }
    }
    
    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed
    javax.swing.table.DefaultTableModel model;
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        boolean a = validarInput();
        if (!a) return;
        model = (javax.swing.table.DefaultTableModel)tabla.getModel();
        idU++;
        Object o[] ={idU, nombre.getText(), precio.getText(), cantMin.getText(), marca.getText()};
        model.addRow(o);

        nombre.setText("");
        precio.setText("");
        cantMin.setText("");
        marca.setText("");
        String s = String.valueOf(model.getValueAt(tabla.getSelectedRow(), 5));
        if( s == "Consumible"){
            consum.setSelected(true);
            no_consum.setSelected(false);
        }else if(s == "No Consumible"){
            consum.setSelected(false);
            no_consum.setSelected(true);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        boolean a = validarInput();
        if(!a) return;
        model.setValueAt(nombre.getText(), tabla.getSelectedRow(), 1);
        model.setValueAt(precio.getText(), tabla.getSelectedRow(), 2);
        model.setValueAt(cantMin.getText(), tabla.getSelectedRow(), 3);
        model.setValueAt(marca.getText(), tabla.getSelectedRow(), 4);
        //model.setValueAt(tipo.getSelectedItem().toString(), tabla.getSelectedRow(), 5);
        
        nombre.setText("");
        precio.setText("");
        cantMin.setText("");
        marca.setText("");
        String s = String.valueOf(model.getValueAt(tabla.getSelectedRow(), 5));
        if( s == "Consumible"){
            consum.setSelected(true);
            no_consum.setSelected(false);
        }else if(s == "No Consumible"){
            consum.setSelected(false);
            no_consum.setSelected(true);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        model = (javax.swing.table.DefaultTableModel)tabla.getModel();
        nombre.setText(String.valueOf(model.getValueAt(tabla.getSelectedRow(), 1)));
        precio.setText(String.valueOf(model.getValueAt(tabla.getSelectedRow(), 2)));
        cantMin.setText(String.valueOf(model.getValueAt(tabla.getSelectedRow(), 3)));
        marca.setText(String.valueOf(model.getValueAt(tabla.getSelectedRow(), 4)));
        String s = String.valueOf(model.getValueAt(tabla.getSelectedRow(), 5));
        if( s == "Consumible"){
            consum.setSelected(true);
            no_consum.setSelected(false);
        }else if(s == "No Consumible"){
            consum.setSelected(false);
            no_consum.setSelected(true);
        }
            
        
        registrar.setEnabled(true);
        modificar.setEnabled(true);
        eliminar.setEnabled(true);
        return;
    }//GEN-LAST:event_tablaMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        model.removeRow(tabla.getSelectedRow());
        eliminar.setEnabled(false);
        modificar.setEnabled(false);
        nombre.setText("");
        precio.setText("");
        cantMin.setText("");
        marca.setText("");
        no_consum.setSelected(false);
        consum.setSelected(false);
        
    }//GEN-LAST:event_eliminarActionPerformed
    ventanaLogin ventanaHome;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ventanaHome.regresar();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void consumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumActionPerformed
        // TODO add your handling code here:
        if (consum.isSelected()==true){
            no_consum.setSelected(false);
        }
    }//GEN-LAST:event_consumActionPerformed

    private void no_consumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_consumActionPerformed
        // TODO add your handling code here:
        if (no_consum.isSelected()==true){
            consum.setSelected(false);
        }
    }//GEN-LAST:event_no_consumActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantMin;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JRadioButton consum;
    private javax.swing.JTextField desc;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JButton modificar;
    private javax.swing.JRadioButton no_consum;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JButton registrar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
